CREATE TYPE ticket_type AS ENUM ('DAY', 'WEEK', 'MONTH', 'YEAR');

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       name VARCHAR NOT NULL,
                       creation_date TIMESTAMP default current_timestamp,
                       PRIMARY KEY (id)
);

CREATE TABLE tickets (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         ticket_type ticket_type NOT NULL,
                         creation_date TIMESTAMP default current_timestamp,
                         PRIMARY KEY (id),
                         FOREIGN KEY(user_id) REFERENCES users(id)
);